### ISSUE TITLE
Add Glastopf version to Hpfeeds log

### ISSUE THREAD

**Issue by nsmfoo** [glastopf/glastopf#169]
Adding version number of the Glastopf instance that generated the log row into the hpfeeds log, would add visibility into which versions is being used/deployed.

This could also be beneficial for other log formats, in cases where people centralize logs from larger installations of Glastopf , I assume they would also benefit from knowing which version they have installed (or rather find those that did not get updated)

**Comment by glaslos** [comment]
fixed with #248

**Comment by katkad** [comment]
this shows, version is not changed a lot https://github.com/mushorg/glastopf/commits/master/glastopf/__init__.py

**Comment by glaslos** [comment]
We have not released in a very long time...
