### ISSUE TITLE
How to Contribute to Handlers

### ISSUE THREAD

**Issue by darkwarriors** [glastopf/glastopf#205]
Hi all,

i hope that this is the correct way to ask some information and some clarifications, i am pretty new in glostopf Honeypot implementantion and i would like to understand how to add my own security knowledge to the detected attacks.

what i would like to better understand is how to add new attacks:
1. i see that there is a .xml that contains all the URI patterns and the module that is responsable to handle that traffic and then trap the attacker attempt.
2 then i see that i have to add new .py class in handlers that react at that pattern and catch all the correct information for logging porpuose

so if i would like to add the new shellsock vulnerability attemtps that try to inject shell or ELF binary throught the user-agent i really dont understand how can i hanlde it, beacuse as i see the only request that is passed to the request and to the classification class is the URI content, am i missing something ? How can i check the body of the request like we see in the Shellshock vuln or cgi-bin/php vuln and then download the specfic binary for further investigation?

forgive my english and i hope that i am asking in the good way all theese information because as i saw there isent a guideline about adding new module or handler.

Regards

**Comment by glaslos** [comment]
Closing this issue as I assume it to be answered.
