### ISSUE TITLE
Integrate Custom Web Application

### ISSUE THREAD

**Issue by dlucenario** [glastopf/glastopf#218]
I have successfully installed Glastopf on my Ubuntu Server(14.04 LTS). Playing with it, it seems that its always looking for the index.html in my myhoneypot/data/templates folder. I wonder if can integrate a web app or a CMS (e.g. Wordpress).

**Comment by glaslos** [comment]
Using a full blown web app would require quite some development work. You can replace the template with one that is just a static version of your cms (single html page).
