### ISSUE TITLE
Glastopf startscript throwing error.

### ISSUE THREAD

**Issue by Waseem-farooqui** [glastopf/glastopf#219]
I am using Honeydrive for the Glastopf and some other honeypots.
When I run the start script from `/usr/local/bin` it throws this error.
![error](https://cloud.githubusercontent.com/assets/10846095/6039286/41414dfc-ac87-11e4-8bea-fd4f4cc2ecb9.png)
I have also updated repositories.
Same script I think works fine over here 
![works](https://cloud.githubusercontent.com/assets/10846095/6039347/f7b47352-ac87-11e4-92d2-2c07a68bf3f7.png)

**Comment by glaslos** [comment]
See here: https://github.com/glastopf/glastopf/issues/216
Should be fixed in the latest version on github.

**Comment by Waseem-farooqui** [comment]
Thanks Its working now by changing by adding 'logstash' section in configurations.
