### ISSUE TITLE
Is there any Management console for visualization of Glastopf ? 

### ISSUE THREAD

**Issue by Waseem-farooqui** [glastopf/glastopf#220]
I have studied about `Glasif` for the visualization of Glastopf but I think it has been obsolete in the new versions of glastopf. 
How can we visualize attacks now ?

**Comment by katkad** [comment]
hello,
I dont know if this will answer your question, but there is https://github.com/vavkamil/Glastopf-Analytics

you can see video in the bottom of the link

**Comment by glaslos** [comment]
Glasif is not compatible with the db schema since many years.
I'd recommend to use something like the ELK stack: http://www.elasticsearch.org/overview/
