### ISSUE TITLE
Want to link phpmyadmin with mysql to get GUI interface for data

### ISSUE THREAD

**Issue by akanshgulati** [glastopf/glastopf#226]
Want to attach phpmyadmin with the glastopf logs which are saved in a mysql database. 
I thought to run Apache at different port and then get phpmyadmin access through it but Apache service is not responding by domain_name:new_port even after I see it running from netstat -tulnp command. 

Please suggest me a way through which I can attach phpmyadmin service with mysql database logging glastopf attacks.

**Comment by glaslos** [comment]
This seems to be an Apache related issue.

**Comment by akanshgulati** [comment]
@glaslos  Thanks for the response sir. I figured out the error. Now apache2 is running at different port. May I know how can I setup phpmyadmin with mysql now?

**Comment by czardoz** [comment]
@akanshgulati, there are a number of tutorials that you can follow: https://www.google.co.in/search?q=set+up+phpmyadmin+with+apache&oq=set+up+phpmyadmin+with+apache&aqs=chrome..69i57j0l3.13449j0j4&client=ms-android-google&sourceid=chrome-mobile&espv=1&ie=UTF-8
