### ISSUE TITLE
Unable to add meta tags of Bing and Google webmaster

### ISSUE THREAD

**Issue by akanshgulati** [glastopf/glastopf#235]
I have already updated the glastopf using "Git pull" command in /opt/glastopf directory. Even after adding the meta details. I am not able to see any success in the source code of the head tag.

##### Sharing the glastopf.cfg.dist file in /opt/glastopf/glastopf folder
```
[mail]
enabled = False
an email notification will be sent only if a specified matched pattern is identified.
Use the wildcard char *, to be notified every time
patterns = rfi,lfi
user =
pwd =
mail_from =
mail_to =
smtp_host = smtp.gmail.com
smtp_port = 587

[taxii]
enabled = False
host = taxiitest.mitre.org
port = 80
inbox_path = /services/inbox/default/
use_https = False
use_auth_basic = False
auth_basic_username = your_username
auth_basic_password = your_password
use_auth_certificate = False
auth_certificate_keyfile = full_path_to_keyfile
auth_certificate_certfile = full_path_to_certfile
include_contact_info = False
contact_name = ...
contact_email = ...

[logstash]
enabled = False
host = localhost
port = 5659
handler = AMQP/TCP/UDP

[misc]
# set webserver banner
banner = Apache/2.0.48

[surface]
#https://www.google.com/webmasters/
google_meta = 8658E02866DDCB241fake
#http://www.bing.com/toolbox/webmaster
bing_meta = 8658E02866DDCB2411fake
```

**Comment by adarshdinesh** [comment]
If its a already build one then after changing the config file delete the Build files like db/ data/ build/ and glastopf.cfg and do a "python setup.py install" again .. I think this will solve your problem.

**Comment by akanshgulati** [comment]
Well yeah, that was the problem. Thanks once again for the support. I would have not taken your this much of time, if I had a idea that it works like this. Is there a good documentation about the structure of glastopf as it will resolve lots of my issues. Thanks once again.

**Comment by adarshdinesh** [comment]
I dont think there is a good documentation. The best way is to read the code and understand that will help you in your project also. All the best
